spring:
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true

server:
  port: 9080

KAFKA_HOST: localhost
KAFKA_PORT: 29092